### ISSUE TITLE
Sign in page!

### ISSUE THREAD

**Issue by GHorningKane** [GHorningKane/comp333ianbartekgavin#58]
Our current sign in page is in HTML. We should create a new one that is in PHP, which actually allows users to sign up. This information will be stored in a table (securely, hashing passwords) using SQL.

**Comment by BartekAlickii** [comment]
- People should be required to register and login with a username and password. If a user enters a username that is already taken, the user should be alerted accordingly and asked to pick a different username. Passwords do not need to be unique. The submitted username and password should be written to the users table of your music-db database. Once people are logged in they should remain authenticated via a PHPSESSID token.
- The registration form should ask people to enter their password twice to ensure that they are not mistaken about what they entered. If the passwords do not match. The user should be prompted again.
- If a user is already logged in and requests the registration page, they should be redirected to the index page with the overview of all rated songs.
- Show at the top of each page in your app which user is logged in.

**Comment by BartekAlickii** [comment]
- All SQL queries must be parameterized to avoid SQL injection attacks.
- Make sure that our stored passwords are not stored in plaintext, but rather hashed and salted! (https://www.okta.com/blog/2019/03/what-are-salted-passwords-and-password-hashing/)
